export const ProductHeader: IProductHeaderProps[] = [
  {
    image: "/images/products/mila6005.jpg",
    title: "Discover the Essence of MI+",
    description: `From cozy family movie nights,
to intense solo gaming marathons,
to unforgettable parties with friends…
MI+ is there — amplifying every moment, every memory.`,
    cta: "Explore Products",
    link: "/products",
  },
  {
    image: `/images/products/telly.png`,
    title: `Innovation Meets Design`,
    description: `MI+ Smart TVs, entertainment steps into the future.
              Crystal-clear display. Bold colors that pop. Sharp details that bring every scene alive.
              Stream. Connect. Play. All in one screen built for the way you live today.`,
    cta: ``,
    link: ``,
  },
  {
    image: `/images/products/mils505.jpg`,
    title: ` Built for Everyday Living`,
    description: `With MI+ Soundbars and Home Theaters, your space becomes more than a room — it
              becomes an experience. Crisp highs. Deep, ground-shaking Sub-Woofers.
              Wireless. Bluetooth. HDMI. USB. Seamlessly designed to keep you connected,
              without the clutter.`,
    cta: `Get in Touch`,
    link: `/contact`,
  },
];

export const allProducts = [
  {
    id: 1,
    name: "MIL6080 Premium Home Theater System",
    image: "/images/products/mil6080.png",
    rating: 4.8,
    reviews: 124,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Experience premium home entertainment with 3.1 surround sound and LED lighting effects",
  },
  {
    id: 2,
    name: "MIL6020B Digital Home Theater System",
    image: "/images/products/mil6020b.jpg",
    rating: 4.9,
    reviews: 89,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Exceptional 3.1 surround sound with elegant blue LED accent lighting",
  },
  {
    id: 3,
    name: "MILA4012 Compact Stereo System",
    image: "/images/products/mila4012-new.jpg",
    rating: 4.8,
    reviews: 134,
    category: "Stereo Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Professional stereo with hexagonal design and premium drivers",
  },
  {
    id: 4,
    name: "MILA6007 Complete Home Theater System",
    image: "/images/products/mila6007.png",
    rating: 4.6,
    reviews: 203,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Complete 5.1 home theater system with comprehensive setup",
  },
  {
    id: 5,
    name: "MIL6090 RGB Gaming Audio System",
    image: "/images/products/mil6090.jpg",
    rating: 4.5,
    reviews: 78,
    category: "Gaming Audio",
    brand: "MI+",
    inStock: true,
    description: "Gaming audio system with spectacular RGB lighting effects",
  },
  {
    id: 6,
    name: "MIL6010B Blue LED Home Theater",
    image: "/images/products/mil6010b.jpg",
    rating: 4.9,
    reviews: 145,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Powerful 3.1 surround sound with striking blue LED lighting",
  },
  {
    id: 7,
    name: "MILS505 Soundbar Collection",
    image: "/images/products/mils505.jpg",
    rating: 4.4,
    reviews: 92,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description: "Versatile soundbar solutions with wireless subwoofer options",
  },
  {
    id: 8,
    name: "MIL6060 Colorful LED Audio System",
    image: "/images/products/mil6060.png",
    rating: 4.7,
    reviews: 167,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Vibrant entertainment system with multi-color LED effects",
  },
  {
    id: 9,
    name: "MIL6030B Teal LED Home Theater",
    image: "/images/products/mil6030b.jpg",
    rating: 4.8,
    reviews: 134,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Elegant teal LED lighting with powerful 3.1 surround sound",
  },
  {
    id: 10,
    name: "MILA6005 Tower Entertainment System",
    image: "/images/products/mila6005.jpg",
    rating: 4.6,
    reviews: 98,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Tower-style entertainment system with comprehensive media playback",
  },
  {
    id: 11,
    name: "MIM6085 Rainbow LED Entertainment System",
    image: "/images/products/mim6085.jpg",
    rating: 4.5,
    reviews: 123,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Spectacular rainbow LED effects with powerful 5.1 surround sound",
  },
  {
    id: 12,
    name: "MIM662 Multimedia Entertainment Center",
    image: "/images/products/mim602a.jpg",
    rating: 4.4,
    reviews: 76,
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Complete multimedia center with CD player and hexagonal design",
  },
  {
    id: 13,
    name: "MIM602 Blue Ring Multimedia System",
    image: "/images/products/mim662a.jpg",
    rating: 4.5,
    reviews: 67,
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    description: "Advanced multimedia with blue LED ring and CD player",
  },
  {
    id: 14,
    name: "MIG805S Premium Tower Home Theater",
    image: "/images/products/mig805s.jpg",
    rating: 4.9,
    reviews: 45,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Premium 5.1 tower system with blue LED accent and cinematic audio",
  },
  {
    id: 15,
    name: "MIG813S LED Ring Tower System",
    image: "/images/products/mig813s.png",
    rating: 4.7,
    reviews: 52,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Sophisticated tower system with colorful LED ring lighting",
  },
  {
    id: 16,
    name: "MIG815S Professional RGB Tower System",
    image: "/images/products/mig815s.png",
    rating: 4.8,
    reviews: 34,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Professional 5.1 system with RGB LED strips and ultimate audio",
  },
  {
    id: 17,
    name: "MIM6530B-H Blue LED Tower System",
    image: "/images/products/mim6530bh.jpg",
    rating: 4.6,
    reviews: 58,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Elegant tower system with striking blue LED lighting",
  },
  {
    id: 18,
    name: "MIM6065 Advanced Colorful LED System",
    image: "/images/products/mim6065-v2.jpg",
    rating: 4.7,
    reviews: 89,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Advanced colorful LED lighting with enhanced 5.1 audio",
  },
  {
    id: 19,
    name: "MIM663 Enhanced Rainbow Ring System",
    image: "/images/products/mim663a-v2.png",
    rating: 4.6,
    reviews: 71,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Enhanced rainbow ring with improved multimedia capabilities",
  },
  {
    id: 20,
    name: "MIMA6508-H Green Ring Tower System",
    image: "/images/products/mima6508h.jpg",
    rating: 4.5,
    reviews: 46,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Sophisticated tower with green/purple LED ring lighting",
  },
  {
    id: 21,
    name: "MIG803S Blue LED Tower Home Theater",
    image: "/images/products/mig803s.jpg",
    rating: 4.8,
    reviews: 39,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Premium 5.1 tower home theater with blue LED accents",
  },
  {
    id: 22,
    name: "65T1 Mountain Series Ultra HD TV",
    image: "/images/products/65t1-mountain.jpg",
    rating: 4.7,
    reviews: 28,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Stunning 65-inch 4K display with natural color reproduction and smart connectivity",
  },
  {
    id: 23,
    name: "75T1 Abstract Series Ultra HD TV",
    image: "/images/products/75t1-abstract.jpg",
    rating: 4.8,
    reviews: 35,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Premium 75-inch 4K display with vibrant color technology and modern design",
  },
  {
    id: 24,
    name: "MIG9050 Ultimate Tower Home Theater System",
    image: "/images/products/mig9050.jpg",
    rating: 4.9,
    reviews: 42,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Ultimate 3.1 tower system with hexagonal design and rainbow LED ring",
  },
  {
    id: 25,
    name: "85T1 Balloon Series Ultra HD TV",
    image: "/images/products/85t1-balloons.jpg",
    rating: 4.6,
    reviews: 31,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Large 85-inch 4K display with immersive viewing and smart platform",
  },
  {
    id: 26,
    name: "75T1 Mountain Series Ultra HD TV",
    image: "/images/products/75t1-mountain.jpg",
    rating: 4.7,
    reviews: 29,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "75-inch 4K display with natural color reproduction and mountain series design",
  },
  {
    id: 27,
    name: "65T1 Venice Series Smart Television",
    image: "/images/products/65t1-venice.jpg",
    rating: 4.8,
    reviews: 33,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Elegant 65-inch smart TV with sophisticated design inspired by classic architecture",
  },
  {
    id: 28,
    name: "MIGS1801W Professional Soundbar System",
    image: "/images/products/migs1801w.jpg",
    rating: 4.7,
    reviews: 26,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description:
      "Professional soundbar with wireless subwoofer and sleek modern design",
  },
  {
    id: 29,
    name: "55T1-A12 Abstract Series Smart TV",
    image: "/images/products/55t1-a12.jpg",
    rating: 4.6,
    reviews: 18,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "55-inch 4K display with abstract series design and vibrant color reproduction",
  },
  {
    id: 30,
    name: "55T1-B10 Voice Control Smart TV",
    image: "/images/products/55t1-b10-voice.jpg",
    rating: 4.7,
    reviews: 22,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Advanced 55-inch 4K TV with integrated voice control system and smart features",
  },
  {
    id: 31,
    name: "55T1-T5 Steel Stand Smart TV",
    image: "/images/products/55t1-t5-steel.jpg",
    rating: 4.5,
    reviews: 15,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "55-inch 4K TV with premium steel tube stand design and tropical aesthetics",
  },
  {
    id: 32,
    name: "55T1-B1 Eagle Series Smart TV",
    image: "/images/products/55t1-b1.jpg",
    rating: 4.8,
    reviews: 24,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Majestic 55-inch 4K display with eagle series nature-inspired design",
  },
  {
    id: 33,
    name: "55T1-A13 Forest Series Smart TV",
    image: "/images/products/55t1-a13.jpg",
    rating: 4.6,
    reviews: 19,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Natural 55-inch 4K TV with forest-inspired eco-friendly design",
  },
  {
    id: 34,
    name: "55T1-A25 Minimalist Smart TV",
    image: "/images/products/55t1-a25.jpg",
    rating: 4.7,
    reviews: 21,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Elegant 55-inch 4K TV with minimalist design and single-button operation",
  },
  {
    id: 35,
    name: "55T1-B10 Arctic Series Smart TV",
    image: "/images/products/55t1-b10-public.jpg",
    rating: 4.5,
    reviews: 16,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Cool 55-inch 4K display with arctic-inspired design and premium features",
  },
  {
    id: 36,
    name: "55T1-T5 Lake Reflection Smart TV",
    image: "/images/products/55t1-t5-lake.jpg",
    rating: 4.8,
    reviews: 20,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Serene 55-inch 4K TV with lake reflection series design and tranquil viewing",
  },
  {
    id: 37,
    name: "55T1-B1 Eagle Series Public Model",
    image: "/images/products/55t1-b1-public.jpg",
    rating: 4.6,
    reviews: 17,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description:
      "Commercial-grade 55-inch 4K TV with eagle series design and enhanced durability",
  },
  {
    id: 38,
    name: "MIL401 Bluetooth Speaker System",
    image: "/product img/product img/2.1 Home Theater MIL401.jpg",
    rating: 4.4,
    reviews: 23,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "36W powerful 2.1 channel speaker with wooden subwoofer, Bluetooth connectivity, and remote control",
  },
  {
    id: 39,
    name: "MILA4011",
    image: "/product img/product img/2.1 Home Theater MILA4011.png",
    rating: 4.3,
    reviews: 28,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "50W powerful 2.1 Bluetooth speaker with wooden subwoofer and multiple connectivity options",
  },
  {
    id: 40,
    name: "MILA4013",
    image: "/product img/product img/2.1 Home Theater MILA4013.png",
    rating: 4.4,
    reviews: 31,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "50W powerful 2.1 channel speaker with wooden subwoofer and remote control",
  },
  {
    id: 41,
    name: "MILA4015",
    image: "/product img/product img/2.1 Home Theater MILA4015.png",
    rating: 4.5,
    reviews: 26,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "High-power 50W 2.1 Bluetooth speaker featuring wooden subwoofer design",
  },
  {
    id: 42,
    name: "MIL6060",
    image: "/product img/product img/3.1 Home Theater MIL6060.png",
    rating: 4.5,
    reviews: 34,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "70W 3.1 channel home theater system with 6.5-inch wooden subwoofer",
  },
  {
    id: 43,
    name: "MIL601A",
    image: "/images/products/mil601a.jpg",
    rating: 4.5,
    reviews: 37,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "65W 3.1 home theater speaker system with 6.5-inch subwoofer",
  },
  {
    id: 44,
    name: "MIL901A",
    image: "/images/products/mil901a.jpg",
    rating: 4.6,
    reviews: 45,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "65W premium 3.1 home theater system with wooden subwoofer",
  },
  {
    id: 45,
    name: "MIMS708",
    image: "/images/products/mims708.png",
    rating: 4.8,
    reviews: 71,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description: "135W high-performance 2.1 soundbar system",
  },
  {
    id: 46,
    name: "MIMB1502",
    image: "/images/products/mimb1502.jpg",
    rating: 4.3,
    reviews: 28,
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    description: "60W public address system with 15-inch subwoofer and plastic cabinet",
  },
  {
    id: 47,
    name: "MIMB1506",
    image: "/images/products/mimb1506.png",
    rating: 4.4,
    reviews: 31,
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    description: "60W PA system featuring 15-inch subwoofer and multiple inputs",
  },
  {
    id: 48,
    name: "MI-A23S195",
    image: "/TV/TV/MI-A23S195.png",
    rating: 4.2,
    reviews: 36,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "23\" LED Music TV with HDMI and USB connectivity",
  },
  {
    id: 49,
    name: "MI-D32F1MC",
    image: "/TV/TV/MI-D32F1MC.jpg",
    rating: 4.4,
    reviews: 42,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" FHD Frameless LED TV with 3x HDMI and USB",
  },
  {
    id: 50,
    name: "MI-Y32K6A",
    image: "/TV/TV/MI-Y32K6A.jpg",
    rating: 4.3,
    reviews: 38,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" FHD Frameless LED TV featuring 3x HDMI inputs",
  },
  {
    id: 51,
    name: "MI-S32T1A",
    image: "/TV/TV/MI-S32T1A.jpg",
    rating: 4.5,
    reviews: 51,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" SMART TV with Wisdom Share, FHD Frameless design",
  },
  {
    id: 52,
    name: "MI-S43T1MXW",
    image: "/TV/TV/MI-S43T1MXW.jpg",
    rating: 4.6,
    reviews: 63,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "43\" SMART TV with WhaleOS and FHD Frameless display",
  },
  {
    id: 53,
    name: "MI-S65T1V",
    image: "/TV/TV/TV-S65T1V.jpg",
    rating: 4.8,
    reviews: 94,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "65\" SMART UHD TV with VIDAA OS and Mirror Cast",
  },
];