export const ProductHeader: IProductHeaderProps[] = [
  {
    image: "/images/products/mila6005.jpg",
    title: "Discover the Essence of MI+",
    description: `From cozy family movie nights,
to intense solo gaming marathons,
to unforgettable parties with friends…
MI+ is there — amplifying every moment, every memory.`,
    cta: "Explore Products",
    link: "/products",
  },
  {
    image: `/images/products/telly.png`,
    title: `Innovation Meets Design`,
    description: `MI+ Smart TVs, entertainment steps into the future.
              Crystal-clear display. Bold colors that pop. Sharp details that bring every scene alive.
              Stream. Connect. Play. All in one screen built for the way you live today.`,
    cta: ``,
    link: ``,
  },
  {
    image: `/images/products/mils505.jpg`,
    title: ` Built for Everyday Living`,
    description: `With MI+ Soundbars and Home Theaters, your space becomes more than a room — it
              becomes an experience. Crisp highs. Deep, ground-shaking Sub-Woofers.
              Wireless. Bluetooth. HDMI. USB. Seamlessly designed to keep you connected,
              without the clutter.`,
    cta: `Get in Touch`,
    link: `/contact`,
  },
];

export const allProducts = [
  {
    id: 1,
    name: "MIL6080",
    image: "/images/products/mil6080.png",
    rating: 4.8,
    reviews: 124,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Experience premium home entertainment with 3.1 surround sound and LED lighting effects",
  },
  {
    id: 2,
    name: "MIL6020B",
    image: "/images/products/mil6020b.jpg",
    rating: 4.9,
    reviews: 89,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Exceptional 3.1 surround sound with elegant blue LED accent lighting",
  },
  {
    id: 3,
    name: "MILA4012",
    image: "/images/products/mila4012-new.jpg",
    rating: 4.8,
    reviews: 134,
    category: "Stereo Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Professional stereo with hexagonal design and premium drivers",
  },
  {
    id: 4,
    name: "MILA6007",
    image: "/images/products/mila6007.png",
    rating: 4.6,
    reviews: 203,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Complete 5.1 home theater system with comprehensive setup",
  },
  {
    id: 5,
    name: "MIL6090",
    image: "/images/products/mil6090.jpg",
    rating: 4.5,
    reviews: 78,
    category: "Gaming Audio",
    brand: "MI+",
    inStock: true,
    description: "Gaming audio system with spectacular RGB lighting effects",
  },
  {
    id: 6,
    name: "MIL6010B",
    image: "/images/products/mil6010b.jpg",
    rating: 4.9,
    reviews: 145,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Powerful 3.1 surround sound with striking blue LED lighting",
  },
  {
    id: 7,
    name: "MILS505",
    image: "/images/products/mils505.jpg",
    rating: 4.4,
    reviews: 92,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description: "Versatile soundbar solutions with wireless subwoofer options",
  },
  {
    id: 8,
    name: "MIL6060",
    image: "/images/products/mil6060.png",
    rating: 4.7,
    reviews: 167,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Vibrant entertainment system with multi-color LED effects",
  },
  {
    id: 9,
    name: "MIL6030B",
    image: "/images/products/mil6030b.jpg",
    rating: 4.8,
    reviews: 134,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Elegant teal LED lighting with powerful 3.1 surround sound",
  },
  {
    id: 10,
    name: "MILA6005",
    image: "/images/products/mila6005.jpg",
    rating: 4.6,
    reviews: 98,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Tower-style entertainment system with comprehensive media playback",
  },
  {
    id: 11,
    name: "MIM6085",
    image: "/images/products/mim6085.jpg",
    rating: 4.5,
    reviews: 123,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Spectacular rainbow LED effects with powerful 5.1 surround sound",
  },
  {
    id: 12,
    name: "MIM662",
    image: "/images/products/mim662.jpg",
    rating: 4.4,
    reviews: 76,
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    description:
      "Complete multimedia center with CD player and hexagonal design",
  },
  {
    id: 13,
    name: "MIM602",
    image: "/images/products/mim602.jpg",
    rating: 4.5,
    reviews: 67,
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    description: "Advanced multimedia with blue LED ring and CD player",
  },
  {
    id: 14,
    name: "MIG805S",
    image: "/images/products/mig805s.jpg",
    rating: 4.9,
    reviews: 45,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Premium 5.1 tower system with blue LED accent and cinematic audio",
  },
  {
    id: 15,
    name: "MIG813S",
    image: "/images/products/mig813s.png",
    rating: 4.7,
    reviews: 52,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Sophisticated tower system with colorful LED ring lighting",
  },
  {
    id: 16,
    name: "MIG815S",
    image: "/images/products/mig815s.png",
    rating: 4.8,
    reviews: 34,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Professional 5.1 system with RGB LED strips and ultimate audio",
  },
  {
    id: 17,
    name: "MIM6530B-H",
    image: "/images/products/mim6530bh.jpg",
    rating: 4.6,
    reviews: 58,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Elegant tower system with striking blue LED lighting",
  },
  {
    id: 18,
    name: "MIM6065",
    image: "/images/products/mim6065-v2.jpg",
    rating: 4.7,
    reviews: 89,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Advanced colorful LED lighting with enhanced 5.1 audio",
  },
  {
    id: 19,
    name: "MIM663",
    image: "/images/products/mim663a-v2.png",
    rating: 4.6,
    reviews: 71,
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    description: "Enhanced rainbow ring with improved multimedia capabilities",
  },
  {
    id: 20,
    name: "MIMA6508-H",
    image: "/images/products/mima6508h.jpg",
    rating: 4.5,
    reviews: 46,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Sophisticated tower with green/purple LED ring lighting",
  },
  {
    id: 21,
    name: "MIG803S",
    image: "/images/products/mig803s.jpg",
    rating: 4.8,
    reviews: 39,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description: "Premium 5.1 tower home theater with blue LED accents",
  },
  {
    id: 22,
    name: "MI-S32T1A",
    image: "/images/products/65t1-mountain.jpg",
    rating: 4.7,
    reviews: 28,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" HD TV with DVB-T2/S2 signal and Music TV functionality",
  },
  {
    id: 23,
    name: "MI-S40T1AX",
    image: "/images/products/75t1-abstract.jpg",
    rating: 4.8,
    reviews: 35,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "40\" HD TV with DVB-T2/S2 signal and super bright display",
  },
  {
    id: 24,
    name: "MIG9050",
    image: "/images/products/mig9050.jpg",
    rating: 4.9,
    reviews: 42,
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    description:
      "Ultimate 3.1 tower system with hexagonal design and rainbow LED ring",
  },
  {
    id: 25,
    name: "MI-S43N1A-X",
    image: "/images/products/85t1-balloons.jpg",
    rating: 4.6,
    reviews: 31,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "43\" FHD TV with DVB-T2/S2 signal and enhanced audio",
  },
  {
    id: 26,
    name: "MI-W43T1H",
    image: "/images/products/75t1-mountain.jpg",
    rating: 4.7,
    reviews: 29,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "43\" FHD TV with TV/DVB-T2/S2 signal and overvoltage protection",
  },
  {
    id: 27,
    name: "MI-W43T1X",
    image: "/images/products/65t1-venice.jpg",
    rating: 4.8,
    reviews: 33,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "43\" FHD TV with TV/ATV/DVB.T2/S2 signal and Music TV",
  },
  {
    id: 28,
    name: "MIGS1801W",
    image: "/images/products/migs1801w.jpg",
    rating: 4.7,
    reviews: 26,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description:
      "Professional soundbar with wireless subwoofer and sleek modern design",
  },
  {
    id: 29,
    name: "MI-W50T1X",
    image: "/images/products/55t1-a12.jpg",
    rating: 4.6,
    reviews: 18,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "50\" UHD TV with VIDAA/WEBOS/whale TV and enhanced connectivity",
  },
  {
    id: 30,
    name: "MI-W55T1X",
    image: "/images/products/55t1-b10-voice.jpg",
    rating: 4.7,
    reviews: 22,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "55\" UHD TV with VIDAA/WEBOS/whale TV and 250 cd/m² brightness",
  },
  {
    id: 31,
    name: "MI-W65T1X",
    image: "/images/products/55t1-t5-steel.jpg",
    rating: 4.5,
    reviews: 15,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "65\" UHD TV with VIDAA/WEBOS/whale TV and comprehensive features",
  },
  {
    id: 32,
    name: "MI-W75T1X",
    image: "/images/products/55t1-b1.jpg",
    rating: 4.8,
    reviews: 24,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "75\" UHD TV with VIDAA/WEBOS/whale TV and 280 cd/m² brightness",
  },
  {
    id: 33,
    name: "MI-W85T1X",
    image: "/images/products/55t1-a13.jpg",
    rating: 4.6,
    reviews: 19,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "85\" UHD TV with VIDAA/WEBOS/whale TV and 300 cd/m² brightness",
  },
  {
    id: 34,
    name: "MI-V55T1",
    image: "/images/products/55t1-a25.jpg",
    rating: 4.7,
    reviews: 21,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "55\" UHD/4K TV with voice remote control and multiple connectivity",
  },
  {
    id: 35,
    name: "MI-V50T1",
    image: "/images/products/55t1-b10-public.jpg",
    rating: 4.5,
    reviews: 16,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "50\" UHD/4K TV with voice remote control and premium features",
  },
  {
    id: 36,
    name: "MI-V65T1",
    image: "/images/products/55t1-t5-lake.jpg",
    rating: 4.8,
    reviews: 20,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "65\" UHD/4K TV with voice remote control and 270 cd/m² brightness",
  },
  {
    id: 37,
    name: "MI-V75T1",
    image: "/images/products/55t1-b1-public.jpg",
    rating: 4.6,
    reviews: 17,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "75\" UHD/4K TV with voice remote control and 280 cd/m² brightness",
  },
  {
    id: 38,
    name: "MIL401gi",
    image: "/product img/product img/2.1 Home Theater MIL401.jpg",
    rating: 4.4,
    reviews: 23,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "36W powerful 2.1 channel speaker with wooden subwoofer, Bluetooth connectivity, and remote control",
  },
  {
    id: 39,
    name: "MILA4011",
    image: "/product img/product img/2.1 Home Theater MILA4011.png",
    rating: 4.3,
    reviews: 28,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "50W powerful 2.1 Bluetooth speaker with wooden subwoofer and multiple connectivity options",
  },
  {
    id: 40,
    name: "MILA4013",
    image: "/product img/product img/2.1 Home Theater MILA4013.png",
    rating: 4.4,
    reviews: 31,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "50W powerful 2.1 channel speaker with wooden subwoofer and remote control",
  },
  {
    id: 41,
    name: "MILA4015",
    image: "/product img/product img/2.1 Home Theater MILA4015.png",
    rating: 4.5,
    reviews: 26,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "High-power 50W 2.1 Bluetooth speaker featuring wooden subwoofer design",
  },
  {
    id: 42,
    name: "MIL6060",
    image: "/product img/product img/3.1 Home Theater MIL6060.png",
    rating: 4.5,
    reviews: 34,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "70W 3.1 channel home theater system with 6.5-inch wooden subwoofer",
  },
  {
    id: 43,
    name: "MIL601A",
    image: "/images/products/mil601a.jpg",
    rating: 4.5,
    reviews: 37,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "65W 3.1 home theater speaker system with 6.5-inch subwoofer",
  },
  {
    id: 44,
    name: "MIL901A",
    image: "/images/products/mil901a.jpg",
    rating: 4.6,
    reviews: 45,
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    description: "65W premium 3.1 home theater system with wooden subwoofer",
  },
  {
    id: 45,
    name: "MIMS708",
    image: "/images/products/mims708.png",
    rating: 4.8,
    reviews: 71,
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    description: "135W high-performance 2.1 soundbar system",
  },
  {
    id: 46,
    name: "MIMB1502",
    image: "/images/products/mimb1502.jpg",
    rating: 4.3,
    reviews: 28,
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    description: "60W public address system with 15-inch subwoofer and plastic cabinet",
  },
  {
    id: 47,
    name: "MIMB1506",
    image: "/images/products/mimb1506.png",
    rating: 4.4,
    reviews: 31,
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    description: "60W PA system featuring 15-inch subwoofer and multiple inputs",
  },
  {
    id: 48,
    name: "MI-A23S195",
    image: "/TV/TV/MI-A23S195.png",
    rating: 4.2,
    reviews: 36,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "23\" LED Music TV with HDMI and USB connectivity",
  },
  {
    id: 49,
    name: "MI-F55T06M",
    image: "/TV/TV/Image_20251023123923_497_11.jpg",
    rating: 4.4,
    reviews: 42,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "55\" 4K Interactive Display with infrared touch and A-grade panel",
  },
  {
    id: 50,
    name: "MI-V85T1",
    image: "/TV/TV/MI-Y32K6A.jpg",
    rating: 4.3,
    reviews: 38,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "85\" UHD/4K TV with voice remote control and 300 cd/m² brightness",
  },
  {
    id: 51,
    name: "MI-F65T09M",
    image: "/TV/TV/MI-S32T1A.jpg",
    rating: 4.5,
    reviews: 51,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "65\" 4K Interactive Display with 300 cd/m² brightness and touch screen",
  },
  {
    id: 52,
    name: "MI-F75T09M",
    image: "/TV/TV/MI-S43T1MXW.jpg",
    rating: 4.6,
    reviews: 63,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "75\" 4K Interactive Display with 300 cd/m² brightness and quad-core processor",
  },
  {
    id: 53,
    name: "MI-F86T09M",
    image: "/TV/TV/TV-S65T1V.jpg",
    rating: 4.8,
    reviews: 94,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "86\" 4K Interactive Display with 400W power and professional touch features",
  },
  {
    id: 54,
    name: "MI-D26S19C",
    image: "/TV/TV/MI-A23S195.png",
    rating: 4.2,
    reviews: 36,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "19\" HD TV with AC/DC power and Music TV functionality",
  },
  {
    id: 55,
    name: "MI-D32F1MC",
    image: "/TV/TV/MI-D32F1MC.jpg",
    rating: 4.3,
    reviews: 42,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" HD TV with super bright display and Music TV",
  },
  {
    id: 56,
    name: "MI-Y32K6A",
    image: "/TV/TV/MI-Y32K6A.jpg",
    rating: 4.3,
    reviews: 38,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "32\" HD TV featuring super bright display and Music TV",
  },
  {
    id: 57,
    name: "MI-D43F1MC",
    image: "/TV/TV/Image_20251023123901_496_11.jpg",
    rating: 4.4,
    reviews: 45,
    category: "Television",
    brand: "MI+",
    inStock: true,
    description: "43\" FHD TV with super bright display and Music TV",
  }
];