import { Navigation } from "@/components/navigation";
import { ProductDetail } from "@/components/product-detail";
import { Footer } from "@/components/footer";
import { notFound } from "next/navigation";

const products = [
  {
    id: 1,
    name: "MIL6080 Premium Home Theater System",
    images: [
      "/images/products/mil6080.png",
      "/images/products/mil6080.png",
      "/images/products/mil6080.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 36W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L305*W198*H380",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "36W",
      "Remote Control": "Yes",
      "Box Size": "L305*W198*H380",
    },
  },
  {
    id: 2,
    name: "MIL6020B Digital Home Theater System",
    images: [
      "/images/products/mil6020b.jpg",
      "/images/products/mil6020b.jpg",
      "/images/products/mil6020b.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 3,
    name: "MILA4012 Compact Stereo System",
    images: [
      "/images/products/mila4012.jpg",
      "/images/products/mila4012.jpg",
      "/images/products/mila4012.jpg",
    ],
    category: "Stereo Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 36W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "2.1 Stereo System",
      "Total Power": "36W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 4,
    name: "MILA6007 Complete Home Theater System",
    images: [
      "/images/products/mila6007.png",
      "/images/products/mila6007.png",
      "/images/products/mila6007.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "5.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 5,
    name: "MIL6090 RGB Gaming Audio System",
    images: [
      "/images/products/mil6090.jpg",
      "/images/products/mil6090.jpg",
      "/images/products/mil6090.jpg",
    ],
    category: "Gaming Audio",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "3.1 Gaming Audio System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 6,
    name: "MIL6010B Blue LED Home Theater",
    images: [
      "/images/products/mil6010b.jpg",
      "/images/products/mil6010b.jpg",
      "/images/products/mil6010b.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 7,
    name: "MILS505 Soundbar Collection",
    images: [
      "/images/products/mils505.jpg",
      "/images/products/mils505.jpg",
      "/images/products/mils505.jpg",
    ],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 60W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX, Coaxial, Optical, HDMI",
    ],
    specifications: {
      "System Type": "Soundbar System",
      "Total Power": "60W",
      "Remote Control": "Yes",
      "Box Size": "N/A",
    },
  },
  {
    id: 8,
    name: "MIL6060 Colorful LED Audio System",
    images: [
      "/images/products/mil6060.png",
      "/images/products/mil6060.png",
      "/images/products/mil6060.png",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 70W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L370*W370*H340",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "70W",
      "Remote Control": "Yes",
      "Box Size": "L370*W370*H340",
    },
  },
  {
    id: 9,
    name: "MIL6030B Teal LED Home Theater",
    images: [
      "/images/products/mil6030b.jpg",
      "/images/products/mil6030b.jpg",
      "/images/products/mil6030b.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 80W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L415*W364*H390",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "80W",
      "Remote Control": "Yes",
      "Box Size": "L415*W364*H390",
    },
  },
  {
    id: 10,
    name: "MILA6005 Tower Entertainment System",
    images: [
      "/images/products/mila6005.jpg",
      "/images/products/mila6005.jpg",
      "/images/products/mila6005.jpg",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 80W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L415*W375*H390",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "80W",
      "Remote Control": "Yes",
      "Box Size": "L415*W375*H390",
    },
  },
    {
    id: 11,
    name: "MIM6085 Rainbow LED Entertainment System",
    images: [
      "/images/products/mim6085.jpg",
      "/images/products/mim6085.jpg",
      "/images/products/mim6085.jpg",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 80W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L370*W340*H340",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "80W",
      "Remote Control": "Yes",
      "Box Size": "L370*W340*H340",
    },
  },
  {
    id: 12,
    name: "MIM662 Multimedia Entertainment Center",
    images: [
      "/images/products/mim662.jpg",
      "/images/products/mim662.jpg",
      "/images/products/mim662.jpg",
    ],
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 70W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L380*W322*H416",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "70W",
      "Remote Control": "Yes",
      "Box Size": "L380*W322*H416",
    },
  },
  {
    id: 13,
    name: "MIM602 Blue Ring Multimedia System",
    images: [
      "/images/products/mim602.jpg",
      "/images/products/mim602.jpg",
      "/images/products/mim602.jpg",
    ],
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 70W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L380*W322*H416",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "70W",
      "Remote Control": "Yes",
      "Box Size": "L380*W322*H416",
    },
  },
  {
    id: 14,
    name: "MIG805S Premium Tower Home Theater",
    images: [
      "/images/products/mig805s.jpg",
      "/images/products/mig805s.jpg",
      "/images/products/mig805s.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 65W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L405*W374*H408",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "65W",
      "Remote Control": "Yes",
      "Box Size": "L405*W374*H408",
    },
  },
  {
    id: 15,
    name: "MIG813S LED Ring Tower System",
    images: [
      "/images/products/mig813s.jpg",
      "/images/products/mig813s.jpg",
      "/images/products/mig813s.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 65W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L420*W364*H422",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "65W",
      "Remote Control": "Yes",
      "Box Size": "L420*W364*H422",
    },
  },
  {
    id: 16,
    name: "MIG815S Professional RGB Tower System",
    images: [
      "/images/products/mig815s.jpg",
      "/images/products/mig815s.jpg",
      "/images/products/mig815s.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 65W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L410*W390*H410",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "65W",
      "Remote Control": "Yes",
      "Box Size": "L410*W390*H410",
    },
  },
  {
    id: 17,
    name: "MIM6530B-H Blue LED Tower System",
    images: [
      "/images/products/mim6530b-h.jpg",
      "/images/products/mim6530b-h.jpg",
      "/images/products/mim6530b-h.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 105W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L410*W390*H410",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "105W",
      "Remote Control": "Yes",
      "Box Size": "L410*W390*H410",
    },
  },
  {
    id: 18,
    name: "MIM6065 Advanced Colorful LED System",
    images: [
      "/images/products/mim6065.jpg",
      "/images/products/mim6065.jpg",
      "/images/products/mim6065.jpg",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 105W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L410*W390*H410",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "105W",
      "Remote Control": "Yes",
      "Box Size": "L410*W390*H410",
    },
  },
  {
    id: 19,
    name: "MIM663 Enhanced Rainbow Ring System",
    images: [
      "/images/products/mim663a.jpg",
      "/images/products/mim663a.jpg",
      "/images/products/mim663a.jpg",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 85W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L410*W390*H410",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "85W",
      "Remote Control": "Yes",
      "Box Size": "L410*W390*H410",
    },
  },
  {
    id: 20,
    name: "MIMA6508-H Green Ring Tower System",
    images: [
      "/images/products/mima6508h.jpg",
      "/images/products/mima6508h.jpg",
      "/images/products/mima6508h.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 95W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L468*W398*H400",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "95W",
      "Remote Control": "Yes",
      "Box Size": "L468*W398*H400",
    },
  },
  {
    id: 21,
    name: "MIG803S Blue LED Tower Home Theater",
    images: [
      "/images/products/mig803s.jpg",
      "/images/products/mig803s.jpg",
      "/images/products/mig803s.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 95W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L468*W398*H400",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "95W",
      "Remote Control": "Yes",
      "Box Size": "L468*W398*H400",
    },
  },
  {
    id: 22,
    name: "65T1 Mountain Series Ultra HD TV",
    images: [
      "/images/products/65t1-mountain.jpg",
      "/images/products/65t1-mountain.jpg",
      "/images/products/65t1-mountain.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "65-inch Ultra HD 4K display",
      "Smart TV connectivity",
      "HDR support for vivid colors",
      "Multiple HDMI and USB ports",
      "Sleek modern stand design",
      "Energy-efficient LED backlight",
    ],
    specifications: {
      "Screen Size": "65 inches",
      "Display Type": "LED with HDR support",
      "Smart Features": "Built-in Wi-Fi, streaming apps",
    },
  },
  {
    id: 23,
    name: "75T1 Abstract Series Ultra HD TV",
    images: [
      "/images/products/75t1-abstract.jpg",
      "/images/products/75t1-abstract.jpg",
      "/images/products/75t1-abstract.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "75-inch premium Ultra HD display",
      "Advanced color technology",
      "Smart TV platform",
      "Multiple connectivity options",
      "Premium build quality",
      "Enhanced audio system",
    ],
    specifications: {
      "Screen Size": "75 inches",
      "Display Type": "Premium LED with advanced color",
      "Smart Features": "Advanced smart platform, streaming",
    },
  },
  {
    id: 24,
    name: "MIG9050 Ultimate Tower Home Theater System",
    images: [
      "/images/products/mig9050s.jpg",
      "/images/products/mig9050s.jpg",
      "/images/products/mig9050s.jpg",
    ],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 100W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L436*W376*H396",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "100W",
      "Remote Control": "Yes",
      "Box Size": "L436*W376*H396",
    },
  },
  {
    id: 25,
    name: "85T1 Balloon Series Ultra HD TV",
    images: [
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "Massive 85-inch display",
      "Cinema-quality 4K resolution",
      "Large format viewing experience",
      "Comprehensive smart features",
      "Premium stand design",
      "Advanced connectivity options",
    ],
    specifications: {
      "Screen Size": "85 inches",
      "Display Type": "Large format LED with HDR",
      "Smart Features": "Comprehensive smart platform",
    },
  },
  {
    id: 26,
    name: "75T1 Mountain Series Ultra HD TV",
    images: [
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "75-inch 4K Ultra HD display",
      "Natural color reproduction",
      "Mountain series design",
      "Smart connectivity features",
      "Immersive viewing experience",
      "Modern aesthetic appeal",
    ],
    specifications: {
      "Screen Size": "75 inches",
      "Display Type": "LED with natural color tech",
      "Smart Features": "Smart platform with apps",
    },
  },
  {
    id: 27,
    name: "65T1 Venice Series Smart Television",
    images: [
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "Elegant 65-inch display",
      "Venice series sophistication",
      "Smart television features",
      "Classic-inspired design",
      "Premium viewing quality",
      "Sophisticated aesthetics",
    ],
    specifications: {
      "Screen Size": "65 inches",
      "Display Type": "LED with sophisticated processing",
      "Smart Features": "Smart platform with streaming",
    },
  },
  {
    id: 28,
    name: "MIGS1801W Professional Soundbar System",
    images: [
      "/images/products/migs1801w.jpg",
      "/images/products/migs1801w.jpg",
      "/images/products/migs1801w.jpg",
    ],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    features: [
      "Professional soundbar design",
      "Wireless subwoofer system",
      "Exceptional audio quality",
      "Sleek modern aesthetics",
      "Wall-mount compatibility",
      "Premium build materials",
    ],
    specifications: {
      "System Type": "2.1 Professional Soundbar",
      "Total Power": "200W",
      "Build Quality": "Professional-grade materials",
    },
  },
  {
    id: 29,
    name: "55T1-A12 Abstract Series Smart TV",
    images: [
      "/images/products/55t1-a12.jpg",
      "/images/products/55t1-a12.jpg",
      "/images/products/55t1-a12.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Abstract series design aesthetics",
      "Smart TV platform with apps",
      "Vibrant color reproduction",
      "Modern contemporary styling",
      "Energy-efficient LED technology",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with vibrant color tech",
      "Smart Features": "Smart platform with streaming apps",
    },
  },
  {
    id: 30,
    name: "55T1-B10 Voice Control Smart TV",
    images: [
      "/images/products/55t1-b10-voice.jpg",
      "/images/products/55t1-b10-voice.jpg",
      "/images/products/55t1-b10-voice.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Integrated voice control system",
      "Hands-free operation",
      "Smart TV with voice commands",
      "Advanced connectivity options",
      "Premium audio integration",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with voice control integration",
      "Smart Features": "Voice control, smart platform, streaming",
      "Voice Control": "Built-in voice recognition system",
    },
  },
  {
    id: 31,
    name: "55T1-T5 Steel Stand Smart TV",
    images: [
      "/images/products/55t1-t5-steel.jpg",
      "/images/products/55t1-t5-steel.jpg",
      "/images/products/55t1-t5-steel.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Premium steel tube stand design",
      "Tropical series aesthetics",
      "Robust construction",
      "Smart TV functionality",
      "Stable steel base design",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with tropical color enhancement",
      "Smart Features": "Smart platform with apps",
      "Stand Design": "Premium steel tube construction",
    },
  },
  {
    id: 32,
    name: "55T1-B1 Eagle Series Smart TV",
    images: [
      "/images/products/55t1-b1.jpg",
      "/images/products/55t1-b1.jpg",
      "/images/products/55t1-b1.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Eagle series nature-inspired design",
      "Majestic viewing experience",
      "Smart TV platform",
      "Premium build quality",
      "Nature-enhanced color processing",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with nature color enhancement",
      "Smart Features": "Smart platform with streaming",
    },
  },
  {
    id: 33,
    name: "55T1-A13 Forest Series Smart TV",
    images: [
      "/images/products/55t1-a13.jpg",
      "/images/products/55t1-a13.jpg",
      "/images/products/55t1-a13.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Forest series eco-inspired design",
      "Natural color reproduction",
      "Smart TV with eco features",
      "Forest-themed aesthetics",
      "Energy-efficient operation",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with natural color processing",
      "Smart Features": "Eco-smart platform with apps",
      "Eco Features": "Energy-efficient, eco-friendly materials",
    },
  },
  {
    id: 34,
    name: "55T1-A25 Minimalist Smart TV",
    images: [
      "/images/products/55t1-a25.jpg",
      "/images/products/55t1-a25.jpg",
      "/images/products/55t1-a25.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Minimalist design aesthetics",
      "Single-button operation",
      "Clean modern styling",
      "Streamlined smart features",
      "Elegant simplicity",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with minimalist processing",
      "Smart Features": "Streamlined smart platform",
    },
  },
  {
    id: 35,
    name: "55T1-B10 Arctic Series Smart TV",
    images: [
      "/images/products/55t1-b10-public.jpg",
      "/images/products/55t1-b10-public.jpg",
      "/images/products/55t1-b10-public.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Arctic series cool design",
      "Cool color processing technology",
      "Premium smart features",
      "Arctic-inspired aesthetics",
      "Refreshing visual experience",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with cool color enhancement",
      "Smart Features": "Premium smart platform with apps",
      "Color Processing": "Arctic-inspired cool tones",
    },
  },
  {
    id: 36,
    name: "55T1-T5 Lake Reflection Smart TV",
    images: [
      "/images/products/55t1-t5-lake.jpg",
      "/images/products/55t1-t5-lake.jpg",
      "/images/products/55t1-t5-lake.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Lake reflection series design",
      "Tranquil viewing experience",
      "Reflection processing technology",
      "Peaceful aesthetics",
      "Serene color enhancement",
    ],
    specifications: {
      "Screen Size": "55 inches",
      "Display Type": "LED with reflection processing",
      "Smart Features": "Tranquil smart platform",
      "Special Processing": "Lake reflection color technology",
    },
  },
  {
    id: 37,
    name: "55T1-B1 Eagle Series Public Model",
    images: [
      "/images/products/55t1-b1-public.jpg",
      "/images/products/55t1-b1-public.jpg",
      "/images/products/55t1-b1-public.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "55-inch 4K Ultra HD display",
      "Eagle series public model design",
      "Commercial-grade reliability",
      "Public model build quality",
      "Eagle-inspired aesthetics",
      "Enhanced durability",
    ],
    specifications: {
      "System Type": "5.1 Eagle Series Public Model",
      "Total Power": "210W",
      "Satellite Speakers": "2 x 45W",
      "Center Channel": "50W",
      "LED Effects": "Eagle-inspired dynamic lighting",
    },
  },
    {
    id: 38,
    name: "MIL401 Bluetooth Speaker System",
    images: [
      "/product img/product img/2.1 Home Theater MIL401.jpg",
      "/product img/product img/2.1 Home Theater MIL401.jpg",
      "/product img/product img/2.1 Home Theater MIL401.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 36W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L305*W198*H380",
    ],
    specifications: {
      "System Type": "2.1 Bluetooth Speaker System",
      "Total Power": "36W",
      "Remote Control": "Yes",
      "Box Size": "L305*W198*H380",
    },
  },
  {
    id: 39,
    name: "MILA4011",
    images: [
      "/product img/product img/2.1 Home Theater MILA4011.png",
      "/product img/product img/2.1 Home Theater MILA4011.png",
      "/product img/product img/2.1 Home Theater MILA4011.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "2.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 40,
    name: "MILA4013",
    images: [
      "/product img/product img/2.1 Home Theater MILA4013.png",
      "/product img/product img/2.1 Home Theater MILA4013.png",
      "/product img/product img/2.1 Home Theater MILA4013.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "2.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 41,
    name: "MILA4015",
    images: [
      "/product img/product img/2.1 Home Theater MILA4015.png",
      "/product img/product img/2.1 Home Theater MILA4015.png",
      "/product img/product img/2.1 Home Theater MILA4015.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 50W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 4"',
      "Box Size: L342*W232*H398",
    ],
    specifications: {
      "System Type": "2.1 Home Theater System",
      "Total Power": "50W",
      "Remote Control": "Yes",
      "Box Size": "L342*W232*H398",
    },
  },
  {
    id: 42,
    name: "MIL6060",
    images: [
      "/product img/product img/3.1 Home Theater MIL6060.png",
      "/product img/product img/3.1 Home Theater MIL6060.png",
      "/product img/product img/3.1 Home Theater MIL6060.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 70W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L370*W370*H340",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "70W",
      "Remote Control": "Yes",
      "Box Size": "L370*W370*H340",
    },
  },
  {
    id: 43,
    name: "MIL601A",
    images: [
      "/images/products/mil601a.jpg",
      "/images/products/mil601a.jpg",
      "/images/products/mil601a.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 65W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L405*W374*H408",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "65W",
      "Remote Control": "Yes",
      "Box Size": "L405*W374*H408",
    },
  },
  {
    id: 44,
    name: "MIL901A",
    images: [
      "/images/products/mil901a.jpg",
      "/images/products/mil901a.jpg",
      "/images/products/mil901a.jpg",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 65W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 6.5"',
      "Box Size: L420*W364*H422",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "65W",
      "Remote Control": "Yes",
      "Box Size": "L420*W364*H422",
    },
  },
  {
    id: 45,
    name: "MIMS708",
    images: [
      "/images/products/mims708.png",
      "/images/products/mims708.png",
      "/images/products/mims708.png",
    ],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Wooden Subwoofer",
      "Audio output: 135W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX, Coaxial, Optical, HDMI",
    ],
    specifications: {
      "System Type": "2.1 Soundbar System",
      "Total Power": "135W",
      "Remote Control": "Yes",
      "Box Size": "N/A",
    },
  },
  {
    id: 46,
    name: "MIMB1502",
    images: [
      "/images/products/mimb1502.jpg",
      "/images/products/mimb1502.jpg",
      "/images/products/mimb1502.jpg",
    ],
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Plastic",
      "Audio output: 60W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 15"',
      "Box Size: L460*W370*H630",
    ],
    specifications: {
      "System Type": "Public Address System",
      "Total Power": "60W",
      "Remote Control": "Yes",
      "Box Size": "L460*W370*H630",
    },
  },
  {
    id: 47,
    name: "MIMB1506",
    images: [
      "/images/products/mimb1506.png",
      "/images/products/mimb1506.png",
      "/images/products/mimb1506.png",
    ],
    category: "Public Address",
    brand: "MI+",
    inStock: true,
    features: [
      "Material: Plastic",
      "Audio output: 60W",
      "Remote control: Yes",
      "Connection: Bluetooth, AC/DC, USB, SD, AUX",
      'Subwoofer size: 15"',
      "Box Size: L460*W370*H630",
    ],
    specifications: {
      "System Type": "Public Address System",
      "Total Power": "60W",
      "Remote Control": "Yes",
      "Box Size": "L460*W370*H630",
    },
  },
  {
    id: 48,
    name: "MI-A23S195",
    images: [
      "/TV/TV/MI-A23S195.png",
      "/TV/TV/MI-A23S195.png",
      "/TV/TV/MI-A23S195.png",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "23-inch LED Display",
      "AC/DC Music TV",
      "HDMI Connectivity",
      "USB Port",
      "Music TV Features",
      "Compact Design"
    ],
    specifications: {
      "Screen Size": "23 inches",
      "Display Type": "LED Music TV",
      "Connectivity": "HDMI, USB",
      "Power Supply": "AC/DC"
    },
  },
  {
    id: 49,
    name: "MI-D32F1MC",
    images: [
      "/TV/TV/MI-D32F1MC.jpg",
      "/TV/TV/MI-D32F1MC.jpg",
      "/TV/TV/MI-D32F1MC.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "32-inch FHD Display",
      "Frameless Design",
      "3x HDMI Ports",
      "USB Connectivity",
      "Full HD Resolution",
      "Slim Bezels"
    ],
    specifications: {
      "Screen Size": "32 inches",
      "Display Type": "FHD Frameless LED",
      "HDMI Ports": "3",
      "Resolution": "1920x1080 Full HD"
    },
  },
  {
    id: 50,
    name: "MI-Y32K6A",
    images: [
      "/TV/TV/MI-Y32K6A.jpg",
      "/TV/TV/MI-Y32K6A.jpg",
      "/TV/TV/MI-Y32K6A.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "32-inch FHD Display",
      "Frameless Design",
      "3x HDMI Ports",
      "USB Connectivity",
      "Full HD Resolution",
      "Modern Aesthetics"
    ],
    specifications: {
      "Screen Size": "32 inches",
      "Display Type": "FHD Frameless LED",
      "HDMI Ports": "3",
      "Resolution": "1920x1080 Full HD"
    },
  },
  {
    id: 51,
    name: "MI-S32T1A",
    images: [
      "/TV/TV/MI-S32T1A.jpg",
      "/TV/TV/MI-S32T1A.jpg",
      "/TV/TV/MI-S32T1A.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "32-inch SMART TV",
      "Wisdom Share Feature",
      "FHD Resolution",
      "Frameless Design",
      "3x HDMI Ports",
      "USB Connectivity"
    ],
    specifications: {
      "Screen Size": "32 inches",
      "Display Type": "SMART FHD Frameless",
      "Smart Features": "Wisdom Share",
      "HDMI Ports": "3"
    },
  },
  {
    id: 52,
    name: "MI-S43T1MXW",
    images: [
      "/TV/TV/MI-S43T1MXW.jpg",
      "/TV/TV/MI-S43T1MXW.jpg",
      "/TV/TV/MI-S43T1MXW.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "43-inch SMART TV",
      "WhaleOS Operating System",
      "FHD Resolution",
      "Frameless Design",
      "3x HDMI Ports",
      "USB Connectivity"
    ],
    specifications: {
      "Screen Size": "43 inches",
      "Display Type": "SMART FHD Frameless",
      "Operating System": "WhaleOS",
      "HDMI Ports": "3"
    },
  },
  {
    id: 53,
    name: "MI-S65T1V",
    images: [
      "/TV/TV/TV-S65T1V.jpg",
      "/TV/TV/TV-S65T1V.jpg",
      "/TV/TV/TV-S65T1V.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    features: [
      "65-inch SMART UHD TV",
      "VIDAA Operating System",
      "Ultra HD Resolution",
      "Frameless Design",
      "3x HDMI Ports",
      "USB Connectivity",
      "Mirror Cast Feature"
    ],
    specifications: {
      "Screen Size": "65 inches",
      "Display Type": "SMART UHD Frameless",
      "Operating System": "VIDAA",
      "Resolution": "3840x2160 4K UHD",
      "Special Features": "Mirror Cast"
    },
  }
];



interface ProductPageProps {
  params: Promise<{ id: string }>;
}
export default async function ProductPage({ params }: ProductPageProps) {
  const { id } = await params;
  const product = products.find((p) => p.id === Number.parseInt(id));

  if (!product) {
    notFound();
  }

  return (
    <>
      <ProductDetail product={product} />
    </>
  );
}

export async function generateStaticParams() {
  return products.map((product) => ({
    id: product.id.toString(),
  }));
}