import { Navigation } from "@/components/navigation"
import { ProductDetail } from "@/components/product-detail"
import { Footer } from "@/components/footer"
import { notFound } from "next/navigation"

const products = [
  {
    id: 1,
    name: "MIL6080 Premium Home Theater System",
    images: ["/images/products/mil6080.png", "/images/products/mil6080.png", "/images/products/mil6080.png"],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 15,
    description:
      "Experience premium home entertainment with the MIL6080 3.1 Home Theater System. Features stunning LED lighting effects, digital display, and powerful surround sound for an immersive audio experience.",
    features: [
      "3.1 channel surround sound",
      "Dynamic LED lighting effects",
      "Digital display with remote control",
      "Multiple connectivity options",
      "Wireless subwoofer",
      "Premium audio drivers",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "200W",
      "Satellite Speakers": "2 x 40W",
      "Center Channel": "50W",
      Subwoofer: "70W wireless",
      Connectivity: "Bluetooth, USB, AUX, Optical",
      "LED Effects": "Multi-color dynamic lighting",
      "Remote Control": "Included",
      Warranty: "2 years",
    },
  },
  {
    id: 2,
    name: "MIL6020B Digital Home Theater System",
    images: ["/images/products/mil6020b.jpg", "/images/products/mil6020b.jpg", "/images/products/mil6020b.jpg"],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 12,
    description:
      "The MIL6020B delivers exceptional 3.1 surround sound with elegant blue LED accent lighting. Perfect for modern living rooms with its sleek design and powerful audio performance.",
    features: [
      "3.1 channel audio system",
      "Blue LED accent lighting",
      "Digital display panel",
      "Wireless connectivity",
      "Multiple input options",
      "Compact satellite speakers",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "180W",
      "Satellite Speakers": "2 x 35W",
      "Center Channel": "45W",
      Subwoofer: "65W",
      Connectivity: "Bluetooth, USB, SD Card, AUX",
      Display: "LED Digital Display",
      "LED Lighting": "Blue accent lighting",
      Warranty: "2 years",
    },
  },
  {
    id: 3,
    name: "MILA4012 Compact Stereo System",
    images: ["/images/products/mila4012.jpg", "/images/products/mila4012.jpg", "/images/products/mila4012.jpg"],
    category: "Stereo Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 20,
    description:
      "Compact yet powerful, the MILA4012 stereo system delivers rich sound quality with modern connectivity. Features dual satellite speakers and a central control unit with digital display.",
    features: [
      "2.1 stereo configuration",
      "Digital display with controls",
      "Dual satellite speakers",
      "Multiple connectivity options",
      "Compact design",
      "Remote control included",
    ],
    specifications: {
      "System Type": "2.1 Stereo System",
      "Total Power": "120W",
      "Satellite Speakers": "2 x 30W",
      Subwoofer: "60W",
      Connectivity: "Bluetooth, USB, AUX, FM Radio",
      Display: "LED Digital Display",
      "Remote Control": "Included",
      Warranty: "1 year",
    },
  },
  {
    id: 4,
    name: "MILA6007 Complete Home Theater System",
    images: ["/images/products/mila6007.png", "/images/products/mila6007.png", "/images/products/mila6007.png"],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 8,
    description:
      "Transform your living space with the MILA6007 complete home theater system. Features a comprehensive 5.1 setup with center unit, multiple satellite speakers, and full remote control.",
    features: [
      "Complete 5.1 surround sound",
      "Multiple satellite speakers",
      "Center control unit",
      "Digital display",
      "Full remote control",
      "Multiple input options",
    ],
    specifications: {
      "System Type": "5.1 Home Theater System",
      "Total Power": "250W",
      "Satellite Speakers": "4 x 25W + Center 50W",
      Subwoofer: "100W",
      Connectivity: "Bluetooth, USB, SD Card, AUX",
      Display: "Digital LED Display",
      "Remote Control": "Full function remote",
      Warranty: "2 years",
    },
  },
  {
    id: 5,
    name: "MIL6090 RGB Gaming Audio System",
    images: ["/images/products/mil6090.jpg", "/images/products/mil6090.jpg", "/images/products/mil6090.jpg"],
    category: "Gaming Audio",
    brand: "MI+",
    inStock: true,
    stockCount: 10,
    description:
      "Elevate your gaming experience with the MIL6090 RGB audio system. Features spectacular rainbow LED lighting effects and powerful 3.1 surround sound for immersive gaming and entertainment.",
    features: [
      "RGB rainbow LED effects",
      "3.1 gaming surround sound",
      "Digital control panel",
      "Gaming-optimized audio",
      "Multiple connectivity options",
      "Dynamic lighting modes",
    ],
    specifications: {
      "System Type": "3.1 Gaming Audio System",
      "Total Power": "220W",
      "Satellite Speakers": "2 x 45W",
      "Center Channel": "55W",
      Subwoofer: "75W",
      "LED Effects": "RGB rainbow lighting",
      Connectivity: "Bluetooth, USB, AUX, Optical",
      "Gaming Features": "Enhanced bass for gaming",
      Warranty: "2 years",
    },
  },
  {
    id: 6,
    name: "MIL6010B Blue LED Home Theater",
    images: ["/images/products/mil6010b.jpg", "/images/products/mil6010b.jpg", "/images/products/mil6010b.jpg"],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 14,
    description:
      "The MIL6010B combines powerful 3.1 surround sound with striking blue LED lighting. Features digital display and comprehensive connectivity for all your entertainment needs.",
    features: [
      "3.1 surround sound system",
      "Blue LED lighting effects",
      "Digital display panel",
      "Wireless connectivity",
      "Multiple input options",
      "Elegant design",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "190W",
      "Satellite Speakers": "2 x 40W",
      "Center Channel": "50W",
      Subwoofer: "60W",
      "LED Effects": "Blue dynamic lighting",
      Connectivity: "Bluetooth, USB, AUX, Optical",
      Display: "Digital LED Display",
      Warranty: "2 years",
    },
  },
  {
    id: 7,
    name: "MILS505 Soundbar Collection",
    images: ["/images/products/mils505.jpg", "/images/products/mils505.jpg", "/images/products/mils505.jpg"],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    stockCount: 18,
    description:
      "Versatile soundbar solutions with the MILS505 collection. Available in multiple configurations with wireless subwoofers for enhanced bass and immersive audio experience.",
    features: [
      "Multiple soundbar configurations",
      "Wireless subwoofer options",
      "Sleek modern design",
      "Wall-mountable",
      "Digital connectivity",
      "Remote control included",
    ],
    specifications: {
      "System Type": "2.1 Soundbar System",
      "Total Power": "150W",
      Soundbar: "90W",
      Subwoofer: "60W wireless",
      Connectivity: "Bluetooth, Optical, AUX",
      Mounting: "Wall-mount ready",
      "Remote Control": "Included",
      Warranty: "2 years",
    },
  },
  {
    id: 8,
    name: "MIL6060 Colorful LED Audio System",
    images: ["/images/products/mil6060.png", "/images/products/mil6060.png", "/images/products/mil6060.png"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 11,
    description:
      "Experience vibrant entertainment with the MIL6060 featuring spectacular multi-color LED effects. This 3.1 system delivers powerful audio with stunning visual appeal for parties and entertainment.",
    features: [
      "Multi-color LED light show",
      "3.1 entertainment system",
      "Digital control interface",
      "Party mode lighting",
      "Remote control",
      "Multiple connectivity options",
    ],
    specifications: {
      "System Type": "3.1 Entertainment System",
      "Total Power": "210W",
      "Satellite Speakers": "2 x 45W",
      "Center Channel": "50W",
      Subwoofer: "70W",
      "LED Effects": "Multi-color dynamic lighting",
      Connectivity: "Bluetooth, USB, AUX, SD Card",
      "Remote Control": "Full function remote",
      Warranty: "2 years",
    },
  },
  {
    id: 9,
    name: "MIL6030B Teal LED Home Theater",
    images: ["/images/products/mil6030b.jpg", "/images/products/mil6030b.jpg", "/images/products/mil6030b.jpg"],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 9,
    description:
      "The MIL6030B features elegant teal LED lighting with powerful 3.1 surround sound. Perfect for modern homes with its sophisticated design and exceptional audio performance.",
    features: [
      "3.1 surround sound system",
      "Teal LED accent lighting",
      "Digital display",
      "Wireless connectivity",
      "Multiple input options",
      "Modern aesthetic design",
    ],
    specifications: {
      "System Type": "3.1 Home Theater System",
      "Total Power": "185W",
      "Satellite Speakers": "2 x 38W",
      "Center Channel": "48W",
      Subwoofer: "61W",
      "LED Effects": "Teal dynamic lighting",
      Connectivity: "Bluetooth, USB, AUX, Optical",
      Display: "Digital LED Display",
      Warranty: "2 years",
    },
  },
  {
    id: 10,
    name: "MILA6005 Tower Entertainment System",
    images: ["/images/products/mila6005.jpg", "/images/products/mila6005.jpg", "/images/products/mila6005.jpg"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 6,
    description:
      "The MILA6005 tower-style entertainment system offers comprehensive media playback with multiple CD slots, digital display, and powerful 5.1 surround sound for complete home entertainment.",
    features: [
      "Tower-style design",
      "Multiple media slots",
      "5.1 surround sound",
      "Digital display panel",
      "Blue LED accents",
      "Comprehensive connectivity",
    ],
    specifications: {
      "System Type": "5.1 Tower Entertainment System",
      "Total Power": "280W",
      "Satellite Speakers": "4 x 30W + Center 60W",
      Subwoofer: "100W",
      "Media Support": "CD, USB, SD Card",
      "LED Effects": "Blue accent lighting",
      Connectivity: "Bluetooth, USB, AUX, FM Radio",
      Display: "Digital LED Display",
      Warranty: "2 years",
    },
  },
  {
    id: 11,
    name: "MIL6090 Premium RGB Gaming System",
    images: [
      "/images/products/mil6090-new.jpg",
      "/images/products/mil6090-new.jpg",
      "/images/products/mil6090-new.jpg",
    ],
    category: "Gaming Audio",
    brand: "MI+",
    inStock: true,
    stockCount: 12,
    description:
      "Experience next-level gaming with the MIL6090 Premium RGB system featuring spectacular rainbow LED lighting effects, powerful 3.1 surround sound, and gaming-optimized audio performance.",
    features: [
      "Premium RGB rainbow lighting",
      "3.1 gaming surround sound",
      "Digital control panel with display",
      "Gaming-optimized bass response",
      "Multiple connectivity options",
      "Dynamic lighting synchronization",
    ],
    specifications: {
      "System Type": "3.1 Premium Gaming System",
      "Total Power": "240W",
      "Satellite Speakers": "2 x 50W",
      "Center Channel": "60W",
      Subwoofer: "80W",
      "LED Effects": "RGB rainbow dynamic lighting",
      Connectivity: "Bluetooth 5.0, USB, AUX, Optical",
      "Gaming Features": "Enhanced bass, low latency",
      Warranty: "2 years",
    },
  },
  {
    id: 12,
    name: "MILS505 Professional Soundbar System",
    images: [
      "/images/products/mils505-new.jpg",
      "/images/products/mils505-new.jpg",
      "/images/products/mils505-new.jpg",
    ],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    stockCount: 15,
    description:
      "Professional-grade soundbar system with dual configuration options. Features wireless subwoofers, premium drivers, and sleek design perfect for modern entertainment setups.",
    features: [
      "Dual soundbar configurations",
      "Wireless subwoofer systems",
      "Professional-grade drivers",
      "Wall-mount compatibility",
      "Premium build quality",
      "Advanced connectivity",
    ],
    specifications: {
      "System Type": "2.1 Professional Soundbar",
      "Total Power": "180W",
      Soundbar: "120W",
      Subwoofer: "60W wireless",
      Connectivity: "Bluetooth 5.0, Optical, HDMI ARC, AUX",
      Mounting: "Wall-mount brackets included",
      "Driver Configuration": "Premium neodymium drivers",
      Warranty: "3 years",
    },
  },
  {
    id: 13,
    name: "MILA6007 Ultimate Home Theater",
    images: [
      "/images/products/mila6007-new.png",
      "/images/products/mila6007-new.png",
      "/images/products/mila6007-new.png",
    ],
    category: "Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 7,
    description:
      "The ultimate home theater experience with MILA6007. Features comprehensive 5.1 surround sound, advanced digital processing, and complete remote control for professional-grade entertainment.",
    features: [
      "Ultimate 5.1 surround sound",
      "Advanced digital processing",
      "Professional satellite speakers",
      "Comprehensive remote control",
      "Multiple input options",
      "Theater-grade audio quality",
    ],
    specifications: {
      "System Type": "5.1 Ultimate Home Theater",
      "Total Power": "300W",
      "Satellite Speakers": "4 x 35W + Center 70W",
      Subwoofer: "120W",
      Connectivity: "Bluetooth, USB, SD Card, AUX, Optical",
      Display: "Digital LED Display",
      "Remote Control": "Advanced multi-function remote",
      Warranty: "3 years",
    },
  },
  {
    id: 14,
    name: "MILA6005 Professional Tower System",
    images: [
      "/images/products/mila6005-new.jpg",
      "/images/products/mila6005-new.jpg",
      "/images/products/mila6005-new.jpg",
    ],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 5,
    description:
      "Professional tower entertainment system with multiple media slots, advanced digital display, and powerful 5.1 surround sound. Perfect for comprehensive home entertainment needs.",
    features: [
      "Professional tower design",
      "Multiple CD/media slots",
      "Advanced 5.1 surround sound",
      "Professional digital display",
      "Blue LED accent lighting",
      "Comprehensive media support",
    ],
    specifications: {
      "System Type": "5.1 Professional Tower System",
      "Total Power": "320W",
      "Satellite Speakers": "4 x 35W + Center 70W",
      Subwoofer: "110W",
      "Audio Processing": "Digital signal processing",
      Connectivity: "Bluetooth, USB, SD Card, AUX, Optical",
      "Remote Control": "Advanced multi-function remote",
      Warranty: "3 years",
    },
  },
  {
    id: 15,
    name: "MIM6085 Rainbow LED Entertainment System",
    images: ["/images/products/mim6085.jpg", "/images/products/mim6085.jpg", "/images/products/mim6085.jpg"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 10,
    description:
      "Spectacular entertainment system featuring vibrant rainbow LED lighting effects and powerful 5.1 surround sound. Perfect for parties and immersive entertainment experiences.",
    features: [
      "Vibrant rainbow LED effects",
      "5.1 surround sound system",
      "Party mode lighting",
      "Digital control interface",
      "Multiple satellite speakers",
      "Entertainment-optimized audio",
    ],
    specifications: {
      "System Type": "5.1 Entertainment System",
      "Total Power": "260W",
      "Satellite Speakers": "4 x 30W + Center 60W",
      Subwoofer: "100W",
      "LED Effects": "Rainbow dynamic lighting",
      Connectivity: "Bluetooth, USB, AUX, SD Card",
      "Special Features": "Party mode, light synchronization",
      Warranty: "2 years",
    },
  },
  {
    id: 16,
    name: "MIM6065 Colorful LED Audio System",
    images: ["/images/products/mim6065.jpg", "/images/products/mim6065.jpg", "/images/products/mim6065.jpg"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 13,
    description:
      "Dynamic entertainment system with spectacular colorful LED lighting and powerful 5.1 audio. Features advanced lighting modes and premium sound quality for ultimate entertainment.",
    features: [
      "Spectacular colorful LED lighting",
      "5.1 dynamic audio system",
      "Advanced lighting modes",
      "Digital display panel",
      "Premium sound drivers",
      "Entertainment-focused design",
    ],
    specifications: {
      "System Type": "5.1 Entertainment System",
      "Total Power": "250W",
      "Satellite Speakers": "4 x 28W + Center 58W",
      Subwoofer: "95W",
      "LED Effects": "Multi-color dynamic lighting",
      Connectivity: "Bluetooth, USB, AUX, SD Card",
      "Lighting Modes": "Multiple preset modes",
      Warranty: "2 years",
    },
  },
  {
    id: 17,
    name: "MIM602A Multimedia Entertainment Center",
    images: ["/images/products/mim602a.jpg", "/images/products/mim602a.jpg", "/images/products/mim602a.jpg"],
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 8,
    description:
      "Complete multimedia entertainment center with hexagonal speaker design, digital display, CD player, and comprehensive connectivity. Perfect for all your entertainment needs.",
    features: [
      "Hexagonal speaker design",
      "Built-in CD player",
      "Digital display with clock",
      "Comprehensive connectivity",
      "Remote control included",
      "Premium build quality",
    ],
    specifications: {
      "System Type": "Multimedia Entertainment Center",
      "Total Power": "160W",
      "Speaker Configuration": "2.1 with hexagonal design",
      Subwoofer: "80W",
      "Media Support": "CD, USB, SD Card, FM Radio",
      Connectivity: "Bluetooth, USB, AUX, FM Radio",
      Display: "Digital LED with clock function",
      Warranty: "2 years",
    },
  },
  {
    id: 18,
    name: "MIM663A Rainbow Ring Audio System",
    images: ["/images/products/mim663a.png", "/images/products/mim663a.png", "/images/products/mim663a.png"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 11,
    description:
      "Stunning audio system featuring a rainbow LED ring design with powerful multimedia capabilities. Combines exceptional sound quality with mesmerizing visual effects.",
    features: [
      "Rainbow LED ring lighting",
      "Multimedia audio system",
      "Digital display interface",
      "Premium sound quality",
      "Multiple connectivity options",
      "Striking visual design",
    ],
    specifications: {
      "System Type": "Multimedia Audio System",
      "Total Power": "200W",
      "Speaker Configuration": "2.1 with LED ring",
      Subwoofer: "100W",
      "LED Effects": "Rainbow ring lighting",
      Connectivity: "Bluetooth, USB, AUX, SD Card",
      "Special Features": "LED ring synchronization",
      Warranty: "2 years",
    },
  },
  {
    id: 19,
    name: "MILA4012 Professional Stereo System",
    images: [
      "/images/products/mila4012-new.jpg",
      "/images/products/mila4012-new.jpg",
      "/images/products/mila4012-new.jpg",
    ],
    category: "Stereo Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 16,
    description:
      "Professional-grade stereo system with hexagonal design elements, digital display, and powerful 2.1 audio configuration. Perfect for professional and home use.",
    features: [
      "Professional 2.1 configuration",
      "Hexagonal design elements",
      "Digital display panel",
      "Professional-grade drivers",
      "Multiple input options",
      "Premium build quality",
    ],
    specifications: {
      "System Type": "2.1 Professional Stereo System",
      "Total Power": "150W",
      "Satellite Speakers": "2 x 40W",
      Subwoofer: "70W",
      Connectivity: "Bluetooth, USB, AUX, FM Radio",
      Display: "Professional LED display",
      "Build Quality": "Premium materials",
      Warranty: "2 years",
    },
  },
  {
    id: 20,
    name: "MIM662A Blue Ring Multimedia System",
    images: ["/images/products/mim662a.jpg", "/images/products/mim662a.jpg", "/images/products/mim662a.jpg"],
    category: "Multimedia Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 9,
    description:
      "Advanced multimedia system featuring blue LED ring lighting, comprehensive media support, and powerful audio performance. Includes CD player and full remote control.",
    features: [
      "Blue LED ring lighting",
      "Built-in CD player",
      "Comprehensive media support",
      "Digital display with controls",
      "Full remote control",
      "Premium audio drivers",
    ],
    specifications: {
      "System Type": "Multimedia System with LED Ring",
      "Total Power": "180W",
      "Speaker Configuration": "2.1 with blue LED ring",
      Subwoofer: "90W",
      "Media Support": "CD, USB, SD Card, FM Radio",
      "LED Effects": "Blue ring lighting",
      Connectivity: "Bluetooth, USB, AUX, FM Radio",
      Warranty: "2 years",
    },
  },
  {
    id: 21,
    name: "MIG805S Premium Tower Home Theater",
    images: ["/images/products/mig805s.jpg", "/images/products/mig805s.jpg", "/images/products/mig805s.jpg"],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 8,
    description:
      "Experience premium home theater with the MIG805S featuring tall tower speakers, center unit with blue LED accent, digital display, and powerful 5.1 surround sound for cinematic audio.",
    features: [
      "Premium 5.1 tower configuration",
      "Tall tower satellite speakers",
      "Blue LED accent lighting",
      "Digital display with remote",
      "Cinematic audio quality",
      "Premium build materials",
    ],
    specifications: {
      "System Type": "5.1 Premium Tower Home Theater",
      "Total Power": "350W",
      "Tower Speakers": "2 x 60W",
      "Center Channel": "80W",
      "Rear Speakers": "2 x 40W",
      Subwoofer: "110W",
      "LED Effects": "Blue accent lighting",
      Connectivity: "Bluetooth 5.0, USB, AUX, Optical, HDMI",
      Warranty: "3 years",
    },
  },
  {
    id: 22,
    name: "MIM6085 Enhanced Rainbow LED System",
    images: ["/images/products/mim6085-v2.jpg", "/images/products/mim6085-v2.jpg", "/images/products/mim6085-v2.jpg"],
    category: "Entertainment Systems",
    brand: "MI+",
    inStock: true,
    stockCount: 12,
    description:
      "Enhanced version of the popular MIM6085 with improved rainbow LED effects and powerful 5.1 surround sound. Perfect for entertainment and party environments with spectacular lighting.",
    features: [
      "Enhanced rainbow LED effects",
      "Improved 5.1 surround sound",
      "Party mode optimization",
      "Digital control interface",
      "Multiple satellite speakers",
      "Advanced lighting synchronization",
    ],
    specifications: {
      "System Type": "5.1 Enhanced Entertainment System",
      "Total Power": "280W",
      "Satellite Speakers": "4 x 35W + Center 65W",
      Subwoofer: "105W",
      "LED Effects": "Enhanced rainbow dynamic lighting",
      Connectivity: "Bluetooth 5.0, USB, AUX, SD Card",
      "Special Features": "Advanced party mode, light sync",
      Warranty: "2 years",
    },
  },
  {
    id: 23,
    name: "MIG9050 Ultimate Tower Home Theater",
    images: ["/images/products/mig9050.jpg", "/images/products/mig9050.jpg", "/images/products/mig9050.jpg"],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 5,
    description:
      "Experience the ultimate in home theater with the MIG9050 featuring tall hexagonal tower speakers, spectacular rainbow LED ring, and powerful 3.1 surround sound for cinematic audio.",
    features: [
      "Ultimate 3.1 tower configuration",
      "Tall hexagonal tower speakers",
      "Spectacular rainbow LED ring",
      "Digital display with time",
      "Premium audio drivers",
      "Cinematic sound quality",
    ],
    specifications: {
      "System Type": "3.1 Ultimate Tower Home Theater",
      "Total Power": "380W",
      "Tower Speakers": "2 x 80W hexagonal design",
      "Center Channel": "90W",
      Subwoofer: "130W",
      "LED Effects": "Rainbow ring lighting with sync",
      Connectivity: "Bluetooth 5.0, USB, AUX, Optical, HDMI",
      "Special Features": "Time display, premium drivers",
      Warranty: "3 years",
    },
  },
  {
    id: 24,
    name: "85T1 Large Format Ultra HD Television",
    images: [
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 4,
    description:
      "Experience cinema-quality entertainment at home with the massive 85T1 Ultra HD Television. Features large format display, stunning 4K resolution, and comprehensive smart features.",
    features: [
      "Massive 85-inch display",
      "Cinema-quality 4K resolution",
      "Large format viewing experience",
      "Comprehensive smart features",
      "Premium stand design",
      "Advanced connectivity options",
    ],
    specifications: {
      "Screen Size": "85 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "Large format LED with HDR",
      "Smart Features": "Comprehensive smart platform",
      Connectivity: "4x HDMI, 3x USB, Ethernet, Wi-Fi",
      Audio: "Premium audio system",
      Design: "Large format modern design",
      Warranty: "3 years",
    },
  },
  {
    id: 25,
    name: "75T1 Mountain Series Ultra HD TV",
    images: [
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 7,
    description:
      "Discover breathtaking entertainment with the 75T1 Mountain Series. Features stunning 75-inch 4K display, natural color reproduction, and smart connectivity for immersive viewing.",
    features: [
      "75-inch 4K Ultra HD display",
      "Natural color reproduction",
      "Mountain series design",
      "Smart connectivity features",
      "Immersive viewing experience",
      "Modern aesthetic appeal",
    ],
    specifications: {
      "Screen Size": "75 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with natural color tech",
      "Smart Features": "Smart platform with apps",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Integrated stereo system",
      Series: "Mountain Series design",
      Warranty: "2 years",
    },
  },
  {
    id: 26,
    name: "65T1 Venice Series Smart Television",
    images: [
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 10,
    description:
      "Elegant entertainment with the 65T1 Venice Series Smart Television. Features sophisticated 65-inch display, smart features, and elegant design inspired by classic architecture.",
    features: [
      "Elegant 65-inch display",
      "Venice series sophistication",
      "Smart television features",
      "Classic-inspired design",
      "Premium viewing quality",
      "Sophisticated aesthetics",
    ],
    specifications: {
      "Screen Size": "65 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with sophisticated processing",
      "Smart Features": "Smart platform with streaming",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Premium stereo speakers",
      Series: "Venice Series elegance",
      Warranty: "2 years",
    },
  },
  {
    id: 27,
    name: "MIGS1801W Professional Soundbar System",
    images: ["/images/products/migs1801w.jpg", "/images/products/migs1801w.jpg", "/images/products/migs1801w.jpg"],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    stockCount: 15,
    description:
      "Professional-grade soundbar system with wireless subwoofer. The MIGS1801W delivers exceptional audio quality with sleek design perfect for modern entertainment setups.",
    features: [
      "Professional soundbar design",
      "Wireless subwoofer system",
      "Exceptional audio quality",
      "Sleek modern aesthetics",
      "Wall-mount compatibility",
      "Premium build materials",
    ],
    specifications: {
      "System Type": "2.1 Professional Soundbar",
      "Total Power": "200W",
      Soundbar: "140W",
      Subwoofer: "60W wireless",
      Connectivity: "Bluetooth 5.0, Optical, HDMI ARC, AUX",
      Mounting: "Wall-mount brackets included",
      "Build Quality": "Professional-grade materials",
      Warranty: "3 years",
    },
  },
  {
    id: 31,
    name: "65T1 Ultra HD Smart Television",
    images: [
      "/images/products/65t1-mountain.jpg",
      "/images/products/65t1-mountain.jpg",
      "/images/products/65t1-mountain.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 12,
    description:
      "Experience stunning 65-inch Ultra HD entertainment with the 65T1 Smart Television. Features 4K resolution, smart connectivity, and sleek modern design perfect for any living space.",
    features: [
      "65-inch Ultra HD 4K display",
      "Smart TV connectivity",
      "HDR support for vivid colors",
      "Multiple HDMI and USB ports",
      "Sleek modern stand design",
      "Energy-efficient LED backlight",
    ],
    specifications: {
      "Screen Size": "65 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with HDR support",
      "Smart Features": "Built-in Wi-Fi, streaming apps",
      Connectivity: "3x HDMI, 2x USB, Ethernet, Wi-Fi",
      Audio: "Built-in stereo speakers",
      Stand: "Modern pedestal design",
      Warranty: "2 years",
    },
  },
  {
    id: 32,
    name: "75T1 Premium Ultra HD Television",
    images: [
      "/images/products/75t1-abstract.jpg",
      "/images/products/75t1-abstract.jpg",
      "/images/products/75t1-abstract.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 8,
    description:
      "Immerse yourself in premium entertainment with the 75T1 Ultra HD Television. Features massive 75-inch display, vibrant colors, and advanced smart features for the ultimate viewing experience.",
    features: [
      "75-inch premium Ultra HD display",
      "Advanced color technology",
      "Smart TV platform",
      "Multiple connectivity options",
      "Premium build quality",
      "Enhanced audio system",
    ],
    specifications: {
      "Screen Size": "75 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "Premium LED with advanced color",
      "Smart Features": "Advanced smart platform, streaming",
      Connectivity: "4x HDMI, 3x USB, Ethernet, Wi-Fi",
      Audio: "Enhanced stereo speaker system",
      Design: "Premium modern aesthetics",
      Warranty: "3 years",
    },
  },
  {
    id: 33,
    name: "MIG9050 Ultimate Tower Home Theater",
    images: ["/images/products/mig9050.jpg", "/images/products/mig9050.jpg", "/images/products/mig9050.jpg"],
    category: "Premium Home Theater",
    brand: "MI+",
    inStock: true,
    stockCount: 5,
    description:
      "Experience the ultimate in home theater with the MIG9050 featuring tall hexagonal tower speakers, spectacular rainbow LED ring, and powerful 3.1 surround sound for cinematic audio.",
    features: [
      "Ultimate 3.1 tower configuration",
      "Tall hexagonal tower speakers",
      "Spectacular rainbow LED ring",
      "Digital display with time",
      "Premium audio drivers",
      "Cinematic sound quality",
    ],
    specifications: {
      "System Type": "3.1 Ultimate Tower Home Theater",
      "Total Power": "380W",
      "Tower Speakers": "2 x 80W hexagonal design",
      "Center Channel": "90W",
      Subwoofer: "130W",
      "LED Effects": "Rainbow ring lighting with sync",
      Connectivity: "Bluetooth 5.0, USB, AUX, Optical, HDMI",
      "Special Features": "Time display, premium drivers",
      Warranty: "3 years",
    },
  },
  {
    id: 34,
    name: "85T1 Large Format Ultra HD Television",
    images: [
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
      "/images/products/85t1-balloons.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 4,
    description:
      "Experience cinema-quality entertainment at home with the massive 85T1 Ultra HD Television. Features large format display, stunning 4K resolution, and comprehensive smart features.",
    features: [
      "Massive 85-inch display",
      "Cinema-quality 4K resolution",
      "Large format viewing experience",
      "Comprehensive smart features",
      "Premium stand design",
      "Advanced connectivity options",
    ],
    specifications: {
      "Screen Size": "85 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "Large format LED with HDR",
      "Smart Features": "Comprehensive smart platform",
      Connectivity: "4x HDMI, 3x USB, Ethernet, Wi-Fi",
      Audio: "Premium audio system",
      Design: "Large format modern design",
      Warranty: "3 years",
    },
  },
  {
    id: 35,
    name: "75T1 Mountain Series Ultra HD TV",
    images: [
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
      "/images/products/75t1-mountain.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 7,
    description:
      "Discover breathtaking entertainment with the 75T1 Mountain Series. Features stunning 75-inch 4K display, natural color reproduction, and smart connectivity for immersive viewing.",
    features: [
      "75-inch 4K Ultra HD display",
      "Natural color reproduction",
      "Mountain series design",
      "Smart connectivity features",
      "Immersive viewing experience",
      "Modern aesthetic appeal",
    ],
    specifications: {
      "Screen Size": "75 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with natural color tech",
      "Smart Features": "Smart platform with apps",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Integrated stereo system",
      Series: "Mountain Series design",
      Warranty: "2 years",
    },
  },
  {
    id: 36,
    name: "65T1 Venice Series Smart Television",
    images: [
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
      "/images/products/65t1-venice.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 10,
    description:
      "Elegant entertainment with the 65T1 Venice Series Smart Television. Features sophisticated 65-inch display, smart features, and elegant design inspired by classic architecture.",
    features: [
      "Elegant 65-inch display",
      "Venice series sophistication",
      "Smart television features",
      "Classic-inspired design",
      "Premium viewing quality",
      "Sophisticated aesthetics",
    ],
    specifications: {
      "Screen Size": "65 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with sophisticated processing",
      "Smart Features": "Smart platform with streaming",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Premium stereo speakers",
      Series: "Venice Series elegance",
      Warranty: "2 years",
    },
  },
  {
    id: 37,
    name: "MIGS1801W Professional Soundbar System",
    images: ["/images/products/migs1801w.jpg", "/images/products/migs1801w.jpg", "/images/products/migs1801w.jpg"],
    category: "Soundbars",
    brand: "MI+",
    inStock: true,
    stockCount: 15,
    description:
      "Professional-grade soundbar system with wireless subwoofer. The MIGS1801W delivers exceptional audio quality with sleek design perfect for modern entertainment setups.",
    features: [
      "Professional soundbar design",
      "Wireless subwoofer system",
      "Exceptional audio quality",
      "Sleek modern aesthetics",
      "Wall-mount compatibility",
      "Premium build materials",
    ],
    specifications: {
      "System Type": "2.1 Professional Soundbar",
      "Total Power": "200W",
      Soundbar: "140W",
      Subwoofer: "60W wireless",
      Connectivity: "Bluetooth 5.0, Optical, HDMI ARC, AUX",
      Mounting: "Wall-mount brackets included",
      "Build Quality": "Professional-grade materials",
      Warranty: "3 years",
    },
  },
  {
    id: 38,
    name: "55T1-A12 Abstract Series Smart TV",
    images: ["/images/products/55t1-a12.jpg", "/images/products/55t1-a12.jpg", "/images/products/55t1-a12.jpg"],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 15,
    description:
      "Experience artistic entertainment with the 55T1-A12 Abstract Series. Features stunning 55-inch 4K display with vibrant abstract visuals, smart connectivity, and modern design perfect for contemporary spaces.",
    features: [
      "55-inch 4K Ultra HD display",
      "Abstract series design aesthetics",
      "Smart TV platform with apps",
      "Vibrant color reproduction",
      "Modern contemporary styling",
      "Energy-efficient LED technology",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with vibrant color tech",
      "Smart Features": "Smart platform with streaming apps",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Built-in stereo speakers",
      Series: "Abstract Series design",
      Warranty: "2 years",
    },
  },
  {
    id: 39,
    name: "55T1-B10 Voice Control Smart TV",
    images: [
      "/images/products/55t1-b10-voice.jpg",
      "/images/products/55t1-b10-voice.jpg",
      "/images/products/55t1-b10-voice.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 12,
    description:
      "Advanced voice-controlled entertainment with the 55T1-B10. Features 55-inch 4K display, integrated voice control system, and smart features for hands-free operation and convenience.",
    features: [
      "55-inch 4K Ultra HD display",
      "Integrated voice control system",
      "Hands-free operation",
      "Smart TV with voice commands",
      "Advanced connectivity options",
      "Premium audio integration",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with voice control integration",
      "Smart Features": "Voice control, smart platform, streaming",
      "Voice Control": "Built-in voice recognition system",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Enhanced stereo with voice processing",
      Warranty: "2 years",
    },
  },
  {
    id: 40,
    name: "55T1-T5 Steel Stand Smart TV",
    images: [
      "/images/products/55t1-t5-steel.jpg",
      "/images/products/55t1-t5-steel.jpg",
      "/images/products/55t1-t5-steel.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 18,
    description:
      "Tropical entertainment experience with the 55T1-T5 featuring premium steel tube stand design. Combines 55-inch 4K display with robust steel construction for stability and style.",
    features: [
      "55-inch 4K Ultra HD display",
      "Premium steel tube stand design",
      "Tropical series aesthetics",
      "Robust construction",
      "Smart TV functionality",
      "Stable steel base design",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with tropical color enhancement",
      "Smart Features": "Smart platform with apps",
      "Stand Design": "Premium steel tube construction",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Integrated stereo system",
      Warranty: "2 years",
    },
  },
  {
    id: 41,
    name: "55T1-B1 Eagle Series Smart TV",
    images: ["/images/products/55t1-b1.jpg", "/images/products/55t1-b1.jpg", "/images/products/55t1-b1.jpg"],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 14,
    description:
      "Majestic viewing experience with the 55T1-B1 Eagle Series. Features 55-inch 4K display with nature-inspired design, smart connectivity, and premium build quality for immersive entertainment.",
    features: [
      "55-inch 4K Ultra HD display",
      "Eagle series nature-inspired design",
      "Majestic viewing experience",
      "Smart TV platform",
      "Premium build quality",
      "Nature-enhanced color processing",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with nature color enhancement",
      "Smart Features": "Smart platform with streaming",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Premium stereo speakers",
      Series: "Eagle Series design",
      Warranty: "2 years",
    },
  },
  {
    id: 42,
    name: "55T1-A13 Forest Series Smart TV",
    images: ["/images/products/55t1-a13.jpg", "/images/products/55t1-a13.jpg", "/images/products/55t1-a13.jpg"],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 16,
    description:
      "Natural entertainment with the 55T1-A13 Forest Series. Features 55-inch 4K display with forest-inspired aesthetics, smart features, and eco-friendly design for nature lovers.",
    features: [
      "55-inch 4K Ultra HD display",
      "Forest series eco-inspired design",
      "Natural color reproduction",
      "Smart TV with eco features",
      "Forest-themed aesthetics",
      "Energy-efficient operation",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with natural color processing",
      "Smart Features": "Eco-smart platform with apps",
      "Eco Features": "Energy-efficient, eco-friendly materials",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Natural sound stereo system",
      Warranty: "2 years",
    },
  },
  {
    id: 43,
    name: "55T1-A25 Minimalist Smart TV",
    images: ["/images/products/55t1-a25.jpg", "/images/products/55t1-a25.jpg", "/images/products/55t1-a25.jpg"],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 20,
    description:
      "Elegant simplicity with the 55T1-A25 Minimalist design. Features 55-inch 4K display with clean aesthetics, single-button operation, and streamlined smart features for modern living.",
    features: [
      "55-inch 4K Ultra HD display",
      "Minimalist design aesthetics",
      "Single-button operation",
      "Clean modern styling",
      "Streamlined smart features",
      "Elegant simplicity",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with minimalist processing",
      "Smart Features": "Streamlined smart platform",
      Design: "Single-button minimalist operation",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Clean stereo audio system",
      Warranty: "2 years",
    },
  },
  {
    id: 44,
    name: "55T1-B10 Arctic Series Smart TV",
    images: [
      "/images/products/55t1-b10-public.jpg",
      "/images/products/55t1-b10-public.jpg",
      "/images/products/55t1-b10-public.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 13,
    description:
      "Cool elegance with the 55T1-B10 Arctic Series. Features 55-inch 4K display with arctic-inspired design, cool color processing, and premium smart features for refreshing entertainment.",
    features: [
      "55-inch 4K Ultra HD display",
      "Arctic series cool design",
      "Cool color processing technology",
      "Premium smart features",
      "Arctic-inspired aesthetics",
      "Refreshing visual experience",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with cool color enhancement",
      "Smart Features": "Premium smart platform with apps",
      "Color Processing": "Arctic-inspired cool tones",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Premium stereo speakers",
      Warranty: "2 years",
    },
  },
  {
    id: 45,
    name: "55T1-T5 Lake Reflection Smart TV",
    images: [
      "/images/products/55t1-t5-lake.jpg",
      "/images/products/55t1-t5-lake.jpg",
      "/images/products/55t1-t5-lake.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 11,
    description:
      "Serene entertainment with the 55T1-T5 Lake Reflection series. Features 55-inch 4K display with tranquil lake-inspired design, reflection processing, and peaceful viewing experience.",
    features: [
      "55-inch 4K Ultra HD display",
      "Lake reflection series design",
      "Tranquil viewing experience",
      "Reflection processing technology",
      "Peaceful aesthetics",
      "Serene color enhancement",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K Ultra HD)",
      "Display Type": "LED with reflection processing",
      "Smart Features": "Tranquil smart platform",
      "Special Processing": "Lake reflection color technology",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Serene stereo audio system",
      Warranty: "2 years",
    },
  },
  {
    id: 46,
    name: "55T1-B1 Eagle Series Public Model",
    images: [
      "/images/products/55t1-b1-public.jpg",
      "/images/products/55t1-b1-public.jpg",
      "/images/products/55t1-b1-public.jpg",
    ],
    category: "Television",
    brand: "MI+",
    inStock: true,
    stockCount: 17,
    description:
      "Public model excellence with the 55T1-B1 Eagle Series. Features 55-inch 4K display with eagle-inspired design, public model reliability, and commercial-grade build quality.",
    features: [
      "55-inch 4K Ultra HD display",
      "Eagle series public model design",
      "Commercial-grade reliability",
      "Public model build quality",
      "Eagle-inspired aesthetics",
      "Enhanced durability",
    ],
    specifications: {
      "System Type": "5.1 Eagle Series Public Model",
      "Total Power": "210W",
      "Satellite Speakers": "2 x 45W",
      "Center Channel": "50W",
      Subwoofer: "70W",
      "LED Effects": "Eagle-inspired dynamic lighting",
      Connectivity: "3x HDMI, 2x USB, Wi-Fi, Ethernet",
      Audio: "Commercial-grade stereo system",
      Warranty: "3 years commercial warranty",
    },
  },
]

interface ProductPageProps {
  params: Promise<{ id: string }>
}

export default async function ProductPage({ params }: ProductPageProps) {
  const { id } = await params
  const product = products.find((p) => p.id === Number.parseInt(id))

  if (!product) {
    notFound()
  }

  return (
    <div className="min-h-screen bg-white">
      <Navigation />
      <main>
        <ProductDetail product={product} />
      </main>
      <Footer />
    </div>
  )
}

export async function generateStaticParams() {
  return products.map((product) => ({
    id: product.id.toString(),
  }))
}
